// Generated by CoffeeScript 2.0.0-beta4
void function () {
  var f, x;
  f = function () {
    return 'hello';
  };
  f();
  x = function () {
    return 'world';
  };
  x();
}.call(this);
//@ sourceMappingURL=helloworld.jsmap.json